### ISSUE TITLE
Add custom Sidebar to documentation (Docusaurus)

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#112]
We would like to add a custom sidebar to our Docusaurus documentation to take advantage of the type: 'html' field for icons in the contents. 

https://docusaurus.io/docs/sidebar 

Preferred sidebar via custom sidebar:
```
docs
├── Introduction
├── Helpers
│   ├── getCalendarYear
│   └── listDaysInMonths
├── Utilities
│   ├── formatDate
│   ├── getDaysInMonth
│   ├── isValidDay
│   ├── isValidMonth
│   └── isValidYear
├── Road Map
└── Code of Conduct
```

**Comment by Ankan-cyber** [comment]
I can do that assign it to me

**Comment by 9mbs** [comment]
it's all yours @Ankan-cyber :100:
