### ISSUE TITLE
Add MIT license to `workspaces/calendar-widgets` package.json

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#125]
I would like to request that we add the MIT license to the `workspaces/calendar-widgets` package.json file. Currently, the license information is not included in the file. 

https://docs.npmjs.com/cli/v9/configuring-npm/package-json#license

**Comment by bajibpathan** [comment]
@9mbs - Could you please assign this issue to me? I can work on it in case if no one assigned.

Thanks,

**Comment by 9mbs** [comment]
sure thing @bajibpathan! It's all yours. Thank you!
