### ISSUE TITLE
Fix broken links in Docs

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#133]
in #130 we renamed `getCalendarYear` to `listCalendarYear` , shortly after we brought in an update that modifies the sidenav, and now we have a broken link. We need to double back and rename the `/Helpers/getCalendarYear` to `Helpers/listCalendarYear`  in the sidebar.js file so our Docusaurus build can complete successfully. 🙂 

## The build error:
<img width="1044" alt="Screenshot 2023-04-17 at 3 40 20 AM" src="https://user-images.githubusercontent.com/53072963/232461346-98bb9de8-072a-4d20-934c-d23d39f757d8.png">

**Comment by mmnldm** [comment]
Hello there, @9mbs I would like to help fix this issue. Could you please assign me to it?

**Comment by 9mbs** [comment]
sure thing @mmnldm! Thank you for picking this up, feel free to reach out if you have any questions 🙂
