### ISSUE TITLE
npm package 'calendar-widgets' does not provide an export

### ISSUE THREAD

**Issue by Ankan-cyber** [9mbs/calendar-widgets#136]
**I install run in different methods and the same problem persists. and also modify the code in node_modules and same problem**
![issue](https://user-images.githubusercontent.com/81397956/232865495-169e60b7-176d-44e4-9746-17a224fc4787.png)

**Comment by 9mbs** [comment]
Hi @Ankan-cyber 👋  I'm sorry you had to encounter this! To help me better understand the issue, what version of Calendar-Widgets are you currently using? 

I'm thinking this may have something to do with some modifications made in the latest release but wanted to confirm before I push an update.

**Comment by Ankan-cyber** [comment]
Calendar widgets version 0.0.10

**Comment by Ankan-cyber** [comment]
Before pushing the latest updates I tested earlier it works fine but now even if I manually change to an older version the same error persists

**Comment by 9mbs** [comment]
Okay thank you! I am getting ready to release a new version that should address some bundling issues. One thing to note with the next versions & moving forward is this package will only work in React environments because of the `peerDependenceis` that will be required. See #137 for more info 🙂

**Comment by 9mbs** [comment]
> Before pushing the latest updates I tested earlier it works fine but now even if I manually change to an older version the same error persists

I think your seeing some bugs that were introduced in v0.0.10 https://www.calendar-widgets.com/changelog#0010. Also note we introduced the `listCalendarMonths` method in v0.0.10, before that it was `getCalendarYear`

**Comment by Ankan-cyber** [comment]
Ooh my bad i couldn't recognise. Yeah the method changed so there's an error forsure
