### ISSUE TITLE
Update styling for ArgDescriptor component in workspaces/tests

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#146]
I'd like to update the styling for the `ArgDescriptor` component located in the `workspaces/docs` directory. The following changes should be applied:

- [ ] The `.arg-description--name` and `.arg-description--type` class names should have:

```css
margin-bottom: 10px
```

- [ ] The `.description` element should have the following properties:

```css
margin-bottom: 10px;
border-bottom: 1px solid var(--ifm-toc-border-color);
padding-bottom: 40px;
```

- [ ] The `.description` class name should be updated to remain consistent with the other class names in this component.

## Expected

![Image](https://user-images.githubusercontent.com/53072963/233082633-34ac4050-171f-408b-8a97-3006194b627e.png)

**Comment by Subham5401** [comment]
Hey there,
I'd like to take this.
