### ISSUE TITLE
Ignore Storybook in `workspaces/calendar-widgets/.npmignore`

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#149]
To ensure that only the necessary files are included in our package, we need to update our .npmignore file to ignore Storybook.

The following changes should be made:

- [ ] Storybook files should be ignored in the `.npmignore` file.

This issue is open to anyone who wants it! Feel free to reach out if you have any questions or encounter any issues. Many thanks!

**Comment by Subham5401** [comment]
Hey,
I'd take this further.
