### ISSUE TITLE
Add Pull Request Template

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#181]
The following should be added to a file titled `.github/PULL_REQUEST_TEMPLATE.md`

👇 Below this line is the markdown template that we should add.👇 
---

## Pre-flight checklist

- [ ] I have read the [Contributing Guidelines on pull requests](https://github.com/9mbs/calendar-widgets/blob/main/CONTRIBUTING.md).
- [ ] I have verified my code does what I expect it too.
- [ ] **If this is a code change**: I have verified there are no linting errors, and there are no build errors. 

## Motivation

_\<Briefly describe the problems you code is solving.\>_

## Related

_\<Include PRs, Issues, and any additional resources realted to your code change here.\>_

**Comment by CHAMP010** [comment]
Assign this to me.

**Comment by 9mbs** [comment]
merged with #198
