### ISSUE TITLE
Disable blank issues

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#203]
Users should not be able to create new blank GitHub issues, instead they should choose from a list of preset options we're working on creating, starting with #202

Example: https://github.com/facebook/docusaurus/blob/main/.github/ISSUE_TEMPLATE/config.yml 

## Tasks
- [ ] Users should not be able to create new blank GitHub issues

**Comment by CHAMP010** [comment]
do we have to disable blank issues only or also add other urls?

**Comment by CHAMP010** [comment]
assign me to disable blank issues
