### ISSUE TITLE
Spelling error in `.github/PULL_REQUEST_TEMPLATE.md`

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#216]
In the Related section of the `PULL_REQUEST_TEMPLATE.md` file, there is a misspelled word that should be corrected. The word **related** was misspelled in the current version. 

Below is a git diff of the expected results:

```diff
- <Include PRs, Issues, and any additional resources realted to your code change here.>
+ <Include PRs, Issues, and any additional resources related to your code change here.>
```

**Comment by samezzz** [comment]
You can merge it now...You're welcome😊

**Comment by 9mbs** [comment]
awesome stuff @samezzz, thank you again for you help! Marking this as closed
