### ISSUE TITLE
rename calendar-widgets-tests directory to tests

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#64]
that shit is long and it doesnt need to be

I believe there is also a script in the `./package.json` file that refrences that folder name, so we'd want to update that as well

**Comment by 1bhavyasingh1** [comment]
Can I work on this

**Comment by 9mbs** [comment]
Awesome stuff @1bhavyasingh1 , i've accepted these changes into the main branch. Thank you!! 💯

**Comment by 1bhavyasingh1** [comment]
Cheers Mate!!
