### ISSUE TITLE
add a contributing.md file for the calendar-widget package

### ISSUE THREAD

**Issue by Ngoakor12** [9mbs/calendar-widgets#68]
Some things that would be helpful to include:
- pnpm is used/needed to contribute
- getting setup on your machine(which commands to run in which order)
- and other general guidelines on contributing

**side note:** nice looking project by the way, I like the idea list , I was also working on a [somewhat similar package](https://github.com/Ngoakor12/date-time-utils) along these lines because of my frustrations in working with the date and times

**Comment by 9mbs** [comment]
@Ngoakor12 thank you for taking the time to put together these suggestions - it's incredibly helpful to see from a fresh perspective. I'll get the ball rolling on the contributing guide ASAP 🙂 

That is some slick stuff in that `date-time-utils` package. It might be super slick to mesh these projects into 1 🤔🤔🤔

**Comment by Ngoakor12** [comment]
> That is some slick stuff in that `date-time-utils` package. It might be super slick to mesh these projects into 1

**I'm definitely down on two conditions:** you lead the way forward(cause I think I'm less experienced with npm packages in general, same with typescript and never touched rollup) and I can have most if not all of the functions in date-time-utils

**My main idea behind the project:** provide well named wrappers/some abstractions for date and time related logic. Add related but missing helpers as and when needed.

Side note, I really like the idea of adding custom well written errors to these helpers.

**Comment by 9mbs** [comment]
Sure that sounds great to me! My only request is that we maintain a goal of consistency across each utility. Everything available to the public should be type-checked, throughly tested, documented and JSDoc'd.  I am happy to help with that process and share my knowledge, it's ultimately just JavaScript with extra steps 🙂 ! 

The main reason I request consistency is to avoid damaging the packages reputation with community comments such as these:

<img width="675" alt="Screenshot 2023-04-10 at 8 17 43 AM" src="https://user-images.githubusercontent.com/53072963/230931124-37e00c1f-23f7-4e9e-948e-9700a30b362e.png">

My long term vision for this package is not in the utilities themselves but in the "widgets" that can be built from these utilities. React is my lang of choice so I figured starting there and seeing how the community feels about it after. 

Here's the one i really want personally, and the main driver of inspiration for me behind the project (the draggable date-events) 🤩 :

<img width="993" alt="Screenshot 2023-04-10 at 8 01 52 AM" src="https://user-images.githubusercontent.com/53072963/230927991-13f9a59f-7889-40da-a706-2726300067ec.png">
<img width="993" alt="Screenshot 2023-04-10 at 8 08 38 AM" src="https://user-images.githubusercontent.com/53072963/230929233-ad8af6ef-0d44-4967-927c-63411edfee26.png">

But I figure if something of that scale is going to be built, we might as well cover all the groundwork needed to get there anyways. e.g 
<img width="993" alt="Screenshot 2023-04-10 at 8 07 06 AM" src="https://user-images.githubusercontent.com/53072963/230929056-c888c52a-6af7-4845-9643-acc1a9714565.png">
<img width="993" alt="Screenshot 2023-04-10 at 8 07 01 AM" src="https://user-images.githubusercontent.com/53072963/230929069-d157d817-4578-495f-9baf-6750411dc8ee.png">


If your down, i'm down! We can connect on discord if you use that https://discord.gg/4qArE7Z4mC 

I think the easiest way to begin would be via a GH issue-based approach. Each merge request, ideally should be tied to a issue that solves a specific problem.

**Comment by Ngoakor12** [comment]
> Sure that sounds great to me! My only request is that we maintain a goal of consistency across each utility. Everything available to the public should be type-checked, throughly tested, documented and JSDoc'd. I am happy to help with that process and share my knowledge, it's ultimately just JavaScript with extra steps slightly_smiling_face !
> 

Consistency is my middle name :slightly_smiling_face: . Testing and Documentation should not be a big issue as well

> The main reason I request consistency is to avoid damaging the packages reputation with community comments such as these:
> 
> <img alt="Screenshot 2023-04-10 at 8 17 43 AM" width="675" src="https://user-images.githubusercontent.com/53072963/230931124-37e00c1f-23f7-4e9e-948e-9700a30b362e.png">
> 

Makes sense... mistakes happen, but responding to those mistakes in a helpful and transparent manner is important(er)

**Comment by Ngoakor12** [comment]
> My long term vision for this package is not in the utilities themselves but in the "widgets" that can be built from these utilities. React is my lang of choice so I figured starting there and seeing how the community feels about it after.
> 
> Here's the one i really want personally, and the main driver of inspiration for me behind the project (the draggable date-events) star_struck :

I see. Question... are the widgets really the end goal or is the end goal really to create your own calendar? I'm asking because if the widgets are the end goals then the main users would be people who want to create calendars, parts of it? 

> If your down, i'm down! We can connect on discord if you use that [discord.gg/4qArE7Z4mC](https://discord.gg/4qArE7Z4mC)
> 
> I think the easiest way to begin would be via a GH issue-based approach. Each merge request, ideally should be tied to a issue that solves a specific problem.

Sounds good to me

**Comment by 9mbs** [comment]
@Ngoakor12 contributing guide has been created. If you happen to encounter any troubles during setup, feel free to reach out I am happy to assist however I can 🙂

**Comment by Ngoakor12** [comment]
no problemo, I'll have a look later today :ok_hand:
