### ISSUE TITLE
fix docs homepage - it should use relative paths not absolute

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#72]
## Strs
1. Navigate to https://www.calendar-widgets.com/ 
2. From the homepage, select any of the links in the https://www.calendar-widgets.com/#helpers section

Actual: Link opens in a new tab
Expected: Link opens in the same tab

**Comment by Ankan-cyber** [comment]
[solved the issue](https://github.com/9mbs/calendar-widgets/pull/84)

**Comment by Akram-Quark** [comment]
## reset _target attribute
I inspected the links and found that the issue was caused by the 'target' attribute on the 'a' tag being set to '_blank'. Changing it to '_parent' resolved the problem.
```html
Before:

<a href="http://example.com" target="_blank">Link</a>

After:

<a href="http://example.com" target="_parent">Link</a>
```

**Comment by Ankan-cyber** [comment]
yeah but the project uses Docusaurus built in attributes to generate links it doesn't work like that you are saying the react doesn't controlling the anchor tag

**Comment by 9mbs** [comment]
Nice investigations @Akram-Quark 💯 thank you for taking the time to look into this issue! It looks like @Ankan-cyber has submitted a MR that resolves the issue. I greatly appreciate the efforts here 💚  Marking this as closed.
