### ISSUE TITLE
Bug: formatDate test is failing

### ISSUE THREAD

**Issue by Ngoakor12** [9mbs/calendar-widgets#89]
The `formatDate` test: `should format a date in the default locale` is failing. It seems to be be picking up my locale(en-ZA) instead of the project's default locale. Seems fixable, if not remove?

See image:
![image](https://user-images.githubusercontent.com/54069197/231267358-1a015b2b-d14e-4ae4-b793-1146353a0c70.png)

**Comment by 9mbs** [comment]
Very interesting to see from another locale! I was unaware it would fail in this manor. We have #70 created which should ultimately resolve this, the `getDefaultLocale` option will be used to create a more predictable development experience and will be required everywhere locales might apply. 

```js
function getDefaultLocale(overrideLocale, fallbackLocale) {
  let userLocale = navigator.language;
  
  if (overrideLocale) {
    userLocale = overrideLocale;
  } else if (!userLocale && fallbackLocale) {
    userLocale = fallbackLocale;
  }
  
  return userLocale;
}
``` 

I tried slapping it in everywhere carelessly and everything broke lol. I'll bump this up on the list of priorities and get it ironed out ASAP.

**Comment by 9mbs** [comment]
@Ngoakor12 i've removed the failing test suite for now, to allow folks in other locales to properly test. This temp fix will allow me to iron out a better solution in #70 🙂 

please let me know if this solves the failing tests in your local env.

**Comment by Ngoakor12** [comment]
> @Ngoakor12 i've removed the failing test suite for now, to allow folks in other locales to properly test. This temp fix will allow me to iron out a better solution in #70 slightly_smiling_face
> 
> please let me know if this solves the failing tests in your local env.

Had a quick look, all the tests are passing :)

Side note: the week was hectic, I will hopefully be able to work on that issue assigned to me and open more

**Comment by 9mbs** [comment]
No worries at all 💯 thank you for taking the time to run these tests again. It's greatly appreciated!
