### ISSUE TITLE
Modify Eslint Rule for Object Curly Spacing

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#97]
Currently, in `workspaces/calendar-widgets` the Eslint rule for object curly spacing is set to "never" in the project's configuration. 

```js
// what we currently have
import {something} from 'somewhere';

// what we want
import { something } from 'somewhere';
```

It has been determined that it would be more consistent with our code style to enforce spacing inside object literals. The Eslint rule for object curly spacing should be modified to `"always"` 

Docs: https://eslint.org/docs/latest/rules/object-curly-spacing

**Comment by 9mbs** [comment]
@giri-madhan thank you for taking the time to contribute to this issue! I've merged these changes to the `main` branch and have closed this ticket.

**Comment by giri-madhan** [comment]
Thank you for the help @9mbs . Welcome!
